// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpigotCaseStudy.Models.DbModels;

namespace SpigotCaseStudy.Migrations
{
    [DbContext(typeof(SpigotCaseStudyDbContext))]
    partial class SpigotCaseStudyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SpigotCaseStudy.Models.DbModels.MediaItem", b =>
                {
                    b.Property<int>("MediaItemId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ApiEndpointId");

                    b.Property<DateTime>("DateCreated");

                    b.Property<DateTime>("DateLastAccessed");

                    b.Property<string>("Description");

                    b.Property<string>("ExternalId");

                    b.Property<string>("ImageUrl");

                    b.Property<string>("KeyWords");

                    b.Property<string>("LargeImageUrl");

                    b.Property<string>("MediaType");

                    b.Property<string>("Title");

                    b.Property<string>("VideoUrl");

                    b.HasKey("MediaItemId");

                    b.ToTable("MediaItems");
                });
#pragma warning restore 612, 618
        }
    }
}
